version: "2"

services:
  kotlib:
    build: .
    ports:
     - 80:80
    volumes:
      - ".:/var/www/html"
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=kotlib_test
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
